import Head from 'next/head'


const About = () => {
        return (
        <>
              <Head>
        <title>Página sobre mí</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
        <div>Hola, este es la típica página de Sobre mi </div>

        </main>
        </>
        )
}

export default About;